### ISSUE TITLE
Is there any plan to publish stix2-matcher in pypi?

### ISSUE THREAD

**Issue by mdazam1942** [oasis-open/cti-pattern-matcher#59]
Apparently pypi can't reach out to URLs outside of PyPi when installing any pypi package(according to https://github.com/pypa/pip/issues/6301). So i'm wondering if there's any plan to publish stix2-matcher in pypi to make this process easier.

**Comment by clenk** [comment]
This tool is more of a demonstration/prototype and not intended in its current state for "real" production use. It's meant more as an example for others to learn from and develop their own production-ready tools.  Thus we've been hesitant to publish this package.

**Comment by JasonKeirstead** [comment]
@clenk Since we are actively going to be using it in production, wondering if you'd be willing to make IBM a co-maintainer to take it fwd from that point of view?

**Comment by fslds** [comment]
The genie might be already out of the bottle, as it is used in some projects without being in PyPi.  Looking at the code itself it looks more than formidable compared to the average PyPi project. Making it available in PyPi will open it up to more feedback and contribution as the usage will increase, making it more stable/mature.

**Comment by mdazam1942** [comment]
stix2-matcher is now published to pypi- https://pypi.org/project/stix2-matcher/
