### ISSUE TITLE
Install requirements error for antlr4-python3-runtime

### ISSUE THREAD

**Issue by mdazam1942** [oasis-open/cti-pattern-matcher#60]
Install requires stated `'antlr4-python3-runtime==4.7 ; python_version >= "3"',` but stix2-patterns has `antlr4-python3-runtime~=4.8.0;` which creates a conflict while installing setup.py. Here's the error-

`ERROR: stix2-patterns 1.3.0 has requirement antlr4-python3-runtime~=4.8.0; python_version >= "3", but you'll have antlr4-python3-runtime 4.7 which is incompatible.`

Is it possible to bump up the version of `antlr4-python3-runtime` to 4.8 ?

**Comment by chisholm** [comment]
I think we need to remove the direct dependency declaration on `antlr4-python3-runtime`, to ensure this doesn't happen.  pattern-matcher should use the pattern-validator's version, whatever that may be.

**Comment by mdazam1942** [comment]
thanks @clenk for the quick fix.
