### ISSUE TITLE
STIX 2.1 support

### ISSUE THREAD

**Issue by pcoccoli** [oasis-open/cti-pattern-matcher#74]
The matcher doesn't appear to work with STIX 2.1 if using `object_refs` instead of a 2.0-style Observable Container.

**Comment by baulus** [comment]
@pcoccoli 
https://github.com/oasis-open/cti-pattern-matcher/pull/76

**Comment by delliott90** [comment]
Closed via https://github.com/oasis-open/cti-pattern-matcher/pull/76
